### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by AlekKras** [r3vn/badKarma#9]
Hello,

This tool seems really nice but I am having a difficulty running it. I am assuming that the issue is quite minor so I was wondering if someone could help me out?

when I run `./badkarma.py` I get the following output:

```

(badkarma.py:8549): dbind-WARNING **: 18:01:21.075: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Traceback (most recent call last):
  File "./badkarma.py", line 25, in <module>
    from core.main import Handler
  File "/home/whoami/Desktop/badKarma/core/main.py", line 37, in <module>
    from core.database import DB
  File "/home/whoami/Desktop/badKarma/core/database.py", line 19, in <module>
    from sqlalchemy import Column, ForeignKey, Integer, String, Text, Boolean, Float
ModuleNotFoundError: No module named 'sqlalchemy'
```

**Comment by r3vn** [comment]
Hi AlekKras,
it's seems that you are missing sqlalchemy dependency,
did you install the python3 requirements?

G.

**Comment by AlekKras** [comment]
Thank you for your response @r3vn ! The problem that I have is that I have sqlalchemy installed and I ran the requirements.txt file to install all necessary requirements. That's why I was curious with the problem since everything appears to be present (and the module is installed) but when running the program, it says the package isn't installed

**Comment by AlekKras** [comment]
So I found out the way to fix it @r3vn ! Took me a long time but here is a quick solution that simply works. 
I downloaded Vagrant and VirtualBox and had a Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "offensive-security/kali-linux-light"
end
```
And then I started the box and it worked well for me. I actually think that it's a a pretty good enhancement since you can hide your IP to perform pen testing without being spotted. I tested this on my Infrastructure as Red Team hacker and Blue Team wasn't able to spot me. So I can do a pull request if you want me to do add this enhancement?

**Comment by r3vn** [comment]
> Thank you for your response @r3vn ! The problem that I have is that I have sqlalchemy installed and I ran the requirements.txt file to install all necessary requirements. That's why I was curious with the problem since everything appears to be present (and the module is installed) but when running the program, it says the package isn't installed

are you sure that sqlalchemy was installed in python3 and not in python2?
requirements should be installed with pip3.


> So I found out the way to fix it @r3vn ! Took me a long time but here is a quick solution that simply works.
> I downloaded Vagrant and VirtualBox and had a Vagrantfile
> 
> ```
> Vagrant.configure("2") do |config|
>   config.vm.box = "offensive-security/kali-linux-light"
> end
> ```
> 
> And then I started the box and it worked well for me. I actually think that it's a a pretty good enhancement since you can hide your IP to perform pen testing without being spotted. I tested this on my Infrastructure as Red Team hacker and Blue Team wasn't able to spot me. So I can do a pull request if you want me to do add this enhancement?

i have no plans for vagrant atm, maybe it could be a good idea for the development branch
